### ISSUE TITLE
Errors in SD-Forge

### ISSUE THREAD

**Issue by kuyin** [huchenlei/sd-webui-controlnet-evaclip#1]
error info:

*** Error loading script: preprocessor_evaclip.py
    Traceback (most recent call last):
      File "I:\GitHub\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "I:\GitHub\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "I:\GitHub\stable-diffusion-webui-forge\extensions\sd-webui-controlnet-evaclip\scripts\preprocessor_evaclip.py", line 13, in <module>
        from internal_controlnet.external_code import Preprocessor, PreprocessorParameter
    ModuleNotFoundError: No module named 'internal_controlnet'

**Comment by huchenlei** [comment]
This extension is not compatible with SD Forge.
